// Code generated by box-cli. YOU CAN EDIT.

package main

import (
	"flag"

	"github.com/tddhit/box/mw"
	"github.com/tddhit/box/transport"
	tropt "github.com/tddhit/box/transport/option"
	"github.com/tddhit/tools/log"

	"github.com/tddhit/xsearch/metad/pb"
	"github.com/tddhit/xsearch/metad/service"
)

var (
	listenAddr string
	pidPath    string
	logPath    string
	logLevel   int
)

func init() {
	flag.StringVar(&listenAddr, "listen-addr", "grpc://:9010", "listen address")
	flag.StringVar(&pidPath, "pidpath", "/var/metad.pid", "pid path")
	flag.StringVar(&logPath, "logpath", "", "log file path")
	flag.IntVar(&logLevel, "loglevel", 1,
		"log level (Trace:1, Debug:2, Info:3, Error:5)")
	flag.Parse()
}

func main() {
	log.Init(logPath, logLevel)
	svc := service.New()
	grpcServer, err := transport.Listen(
		listenAddr,
		tropt.WithUnaryServerMiddleware(
			service.CheckNamespaceWithUnary(svc),
		),
	)
	if err != nil {
		log.Fatal(err)
	}
	grpcServer.Register(metadpb.MetadGrpcServiceDesc, svc)
	mw.Run(mw.WithServer(grpcServer), mw.WithPIDPath(pidPath))
}
