// Code generated by box-cli. YOU CAN EDIT.

package main

import (
	"flag"
	"github.com/tddhit/box/mw"
	"github.com/tddhit/box/transport"
	"github.com/tddhit/tools/log"
	. "github.com/tddhit/xsearch/metad/conf"
	"github.com/tddhit/xsearch/metad/service"
	pb "github.com/tddhit/xsearch/metad/pb"
)

var (
	confPath   string
	grpcAddr string
)

func init() {
	flag.StringVar(&confPath, "conf-path", "conf/metad.yml", "config file")
	flag.StringVar(&grpcAddr, "grpc-addr", "grpc://127.0.0.1:9000", "grpc listen address")
	flag.Parse()
}

func main() {
	var (
		conf  	Conf
		err 	error
		svc interface{}
	)
	NewConf(confPath, &conf)
	log.Init(conf.LogPath, conf.LogLevel)
	if mw.IsWorker() { 
		svc = service.NewService()
	}

	
	// new GRPC Server
	grpcServer, err := transport.Listen(grpcAddr)
	if err != nil {
		log.Fatal(err)
	}
	if mw.IsWorker() { 
		grpcServer.Register(pb.MetadGrpcServiceDesc, svc)
	}
	


	

	

	// run with master-worker
	mw.Run(mw.WithServer(grpcServer))
}
