// Code generated by protoc-gen-box. DO NOT EDIT.
// source: searchd.proto

package searchdpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	tr "github.com/tddhit/box/transport"
	tropt "github.com/tddhit/box/transport/option"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import (
	context1 "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateShardReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ShardID              uint32   `protobuf:"varint,2,opt,name=shardID,proto3" json:"shardID,omitempty"`
	ReplicaID            uint32   `protobuf:"varint,3,opt,name=replicaID,proto3" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShardReq) Reset()         { *m = CreateShardReq{} }
func (m *CreateShardReq) String() string { return proto.CompactTextString(m) }
func (*CreateShardReq) ProtoMessage()    {}
func (*CreateShardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchd_5bc22ff304c158b3, []int{0}
}
func (m *CreateShardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShardReq.Unmarshal(m, b)
}
func (m *CreateShardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShardReq.Marshal(b, m, deterministic)
}
func (dst *CreateShardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShardReq.Merge(dst, src)
}
func (m *CreateShardReq) XXX_Size() int {
	return xxx_messageInfo_CreateShardReq.Size(m)
}
func (m *CreateShardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShardReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShardReq proto.InternalMessageInfo

func (m *CreateShardReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateShardReq) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *CreateShardReq) GetReplicaID() uint32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

type CreateShardRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShardRsp) Reset()         { *m = CreateShardRsp{} }
func (m *CreateShardRsp) String() string { return proto.CompactTextString(m) }
func (*CreateShardRsp) ProtoMessage()    {}
func (*CreateShardRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchd_5bc22ff304c158b3, []int{1}
}
func (m *CreateShardRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShardRsp.Unmarshal(m, b)
}
func (m *CreateShardRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShardRsp.Marshal(b, m, deterministic)
}
func (dst *CreateShardRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShardRsp.Merge(dst, src)
}
func (m *CreateShardRsp) XXX_Size() int {
	return xxx_messageInfo_CreateShardRsp.Size(m)
}
func (m *CreateShardRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShardRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShardRsp proto.InternalMessageInfo

type RemoveShardReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ShardID              uint32   `protobuf:"varint,2,opt,name=shardID,proto3" json:"shardID,omitempty"`
	ReplicaID            uint32   `protobuf:"varint,3,opt,name=replicaID,proto3" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveShardReq) Reset()         { *m = RemoveShardReq{} }
func (m *RemoveShardReq) String() string { return proto.CompactTextString(m) }
func (*RemoveShardReq) ProtoMessage()    {}
func (*RemoveShardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchd_5bc22ff304c158b3, []int{2}
}
func (m *RemoveShardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveShardReq.Unmarshal(m, b)
}
func (m *RemoveShardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveShardReq.Marshal(b, m, deterministic)
}
func (dst *RemoveShardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveShardReq.Merge(dst, src)
}
func (m *RemoveShardReq) XXX_Size() int {
	return xxx_messageInfo_RemoveShardReq.Size(m)
}
func (m *RemoveShardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveShardReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveShardReq proto.InternalMessageInfo

func (m *RemoveShardReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *RemoveShardReq) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *RemoveShardReq) GetReplicaID() uint32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

type RemoveShardRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveShardRsp) Reset()         { *m = RemoveShardRsp{} }
func (m *RemoveShardRsp) String() string { return proto.CompactTextString(m) }
func (*RemoveShardRsp) ProtoMessage()    {}
func (*RemoveShardRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchd_5bc22ff304c158b3, []int{3}
}
func (m *RemoveShardRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveShardRsp.Unmarshal(m, b)
}
func (m *RemoveShardRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveShardRsp.Marshal(b, m, deterministic)
}
func (dst *RemoveShardRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveShardRsp.Merge(dst, src)
}
func (m *RemoveShardRsp) XXX_Size() int {
	return xxx_messageInfo_RemoveShardRsp.Size(m)
}
func (m *RemoveShardRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveShardRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveShardRsp proto.InternalMessageInfo

type SyncShardReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ShardID              uint32   `protobuf:"varint,2,opt,name=shardID,proto3" json:"shardID,omitempty"`
	ReplicaID            uint32   `protobuf:"varint,3,opt,name=replicaID,proto3" json:"replicaID,omitempty"`
	FromNode             string   `protobuf:"bytes,4,opt,name=fromNode,proto3" json:"fromNode,omitempty"`
	ToNode               string   `protobuf:"bytes,5,opt,name=toNode,proto3" json:"toNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncShardReq) Reset()         { *m = SyncShardReq{} }
func (m *SyncShardReq) String() string { return proto.CompactTextString(m) }
func (*SyncShardReq) ProtoMessage()    {}
func (*SyncShardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchd_5bc22ff304c158b3, []int{4}
}
func (m *SyncShardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncShardReq.Unmarshal(m, b)
}
func (m *SyncShardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncShardReq.Marshal(b, m, deterministic)
}
func (dst *SyncShardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncShardReq.Merge(dst, src)
}
func (m *SyncShardReq) XXX_Size() int {
	return xxx_messageInfo_SyncShardReq.Size(m)
}
func (m *SyncShardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncShardReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncShardReq proto.InternalMessageInfo

func (m *SyncShardReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SyncShardReq) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *SyncShardReq) GetReplicaID() uint32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

func (m *SyncShardReq) GetFromNode() string {
	if m != nil {
		return m.FromNode
	}
	return ""
}

func (m *SyncShardReq) GetToNode() string {
	if m != nil {
		return m.ToNode
	}
	return ""
}

type SyncShardRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncShardRsp) Reset()         { *m = SyncShardRsp{} }
func (m *SyncShardRsp) String() string { return proto.CompactTextString(m) }
func (*SyncShardRsp) ProtoMessage()    {}
func (*SyncShardRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchd_5bc22ff304c158b3, []int{5}
}
func (m *SyncShardRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncShardRsp.Unmarshal(m, b)
}
func (m *SyncShardRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncShardRsp.Marshal(b, m, deterministic)
}
func (dst *SyncShardRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncShardRsp.Merge(dst, src)
}
func (m *SyncShardRsp) XXX_Size() int {
	return xxx_messageInfo_SyncShardRsp.Size(m)
}
func (m *SyncShardRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncShardRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncShardRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateShardReq)(nil), "searchdpb.CreateShardReq")
	proto.RegisterType((*CreateShardRsp)(nil), "searchdpb.CreateShardRsp")
	proto.RegisterType((*RemoveShardReq)(nil), "searchdpb.RemoveShardReq")
	proto.RegisterType((*RemoveShardRsp)(nil), "searchdpb.RemoveShardRsp")
	proto.RegisterType((*SyncShardReq)(nil), "searchdpb.SyncShardReq")
	proto.RegisterType((*SyncShardRsp)(nil), "searchdpb.SyncShardRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ tr.Server
var _ tr.ClientConn
var _ tropt.CallOption

type SearchdAdminGrpcClient interface {
	CreateShard(ctx context.Context, in *CreateShardReq, opts ...tropt.CallOption) (*CreateShardRsp, error)
	RemoveShard(ctx context.Context, in *RemoveShardReq, opts ...tropt.CallOption) (*RemoveShardRsp, error)
	SyncShard(ctx context.Context, in *SyncShardReq, opts ...tropt.CallOption) (*SyncShardRsp, error)
}

type searchdAdminGrpcClient struct {
	cc tr.ClientConn
}

func NewSearchdAdminGrpcClient(cc tr.ClientConn) SearchdAdminGrpcClient {
	return &searchdAdminGrpcClient{cc}
}

func (c *searchdAdminGrpcClient) CreateShard(ctx context.Context, in *CreateShardReq, opts ...tropt.CallOption) (*CreateShardRsp, error) {
	out := new(CreateShardRsp)
	err := c.cc.Invoke(ctx, "/searchdpb.SearchdAdmin/CreateShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchdAdminGrpcClient) RemoveShard(ctx context.Context, in *RemoveShardReq, opts ...tropt.CallOption) (*RemoveShardRsp, error) {
	out := new(RemoveShardRsp)
	err := c.cc.Invoke(ctx, "/searchdpb.SearchdAdmin/RemoveShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchdAdminGrpcClient) SyncShard(ctx context.Context, in *SyncShardReq, opts ...tropt.CallOption) (*SyncShardRsp, error) {
	out := new(SyncShardRsp)
	err := c.cc.Invoke(ctx, "/searchdpb.SearchdAdmin/SyncShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type searchdAdminGrpcServiceDesc struct {
	desc *grpc.ServiceDesc
}

func (d *searchdAdminGrpcServiceDesc) Desc() interface{} {
	return d.desc
}

var SearchdAdminGrpcServiceDesc = &searchdAdminGrpcServiceDesc{&_SearchdAdmin_serviceDesc}

// Reference imports to suppress errors if they are not otherwise used.
var _ context1.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// SearchdAdminClient is the client API for SearchdAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchdAdminClient interface {
	CreateShard(ctx context1.Context, in *CreateShardReq, opts ...grpc1.CallOption) (*CreateShardRsp, error)
	RemoveShard(ctx context1.Context, in *RemoveShardReq, opts ...grpc1.CallOption) (*RemoveShardRsp, error)
	SyncShard(ctx context1.Context, in *SyncShardReq, opts ...grpc1.CallOption) (*SyncShardRsp, error)
}

type searchdAdminClient struct {
	cc *grpc1.ClientConn
}

func NewSearchdAdminClient(cc *grpc1.ClientConn) SearchdAdminClient {
	return &searchdAdminClient{cc}
}

func (c *searchdAdminClient) CreateShard(ctx context1.Context, in *CreateShardReq, opts ...grpc1.CallOption) (*CreateShardRsp, error) {
	out := new(CreateShardRsp)
	err := c.cc.Invoke(ctx, "/searchdpb.SearchdAdmin/CreateShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchdAdminClient) RemoveShard(ctx context1.Context, in *RemoveShardReq, opts ...grpc1.CallOption) (*RemoveShardRsp, error) {
	out := new(RemoveShardRsp)
	err := c.cc.Invoke(ctx, "/searchdpb.SearchdAdmin/RemoveShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchdAdminClient) SyncShard(ctx context1.Context, in *SyncShardReq, opts ...grpc1.CallOption) (*SyncShardRsp, error) {
	out := new(SyncShardRsp)
	err := c.cc.Invoke(ctx, "/searchdpb.SearchdAdmin/SyncShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchdAdminServer is the server API for SearchdAdmin service.
type SearchdAdminServer interface {
	CreateShard(context1.Context, *CreateShardReq) (*CreateShardRsp, error)
	RemoveShard(context1.Context, *RemoveShardReq) (*RemoveShardRsp, error)
	SyncShard(context1.Context, *SyncShardReq) (*SyncShardRsp, error)
}

func RegisterSearchdAdminServer(s *grpc1.Server, srv SearchdAdminServer) {
	s.RegisterService(&_SearchdAdmin_serviceDesc, srv)
}

func _SearchdAdmin_CreateShard_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchdAdminServer).CreateShard(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/searchdpb.SearchdAdmin/CreateShard",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(SearchdAdminServer).CreateShard(ctx, req.(*CreateShardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchdAdmin_RemoveShard_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveShardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchdAdminServer).RemoveShard(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/searchdpb.SearchdAdmin/RemoveShard",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(SearchdAdminServer).RemoveShard(ctx, req.(*RemoveShardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchdAdmin_SyncShard_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncShardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchdAdminServer).SyncShard(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/searchdpb.SearchdAdmin/SyncShard",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(SearchdAdminServer).SyncShard(ctx, req.(*SyncShardReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchdAdmin_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "searchdpb.SearchdAdmin",
	HandlerType: (*SearchdAdminServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "CreateShard",
			Handler:    _SearchdAdmin_CreateShard_Handler,
		},
		{
			MethodName: "RemoveShard",
			Handler:    _SearchdAdmin_RemoveShard_Handler,
		},
		{
			MethodName: "SyncShard",
			Handler:    _SearchdAdmin_SyncShard_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "searchd.proto",
}

func init() { proto.RegisterFile("searchd.proto", fileDescriptor_searchd_5bc22ff304c158b3) }

var fileDescriptor_searchd_5bc22ff304c158b3 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x4d, 0x2c,
	0x4a, 0xce, 0x48, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x72, 0x0b, 0x92, 0x94,
	0xd2, 0xb8, 0xf8, 0x9c, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x83, 0x33, 0x12, 0x8b, 0x52, 0x82, 0x52,
	0x0b, 0x85, 0x64, 0xb8, 0x38, 0xf3, 0x12, 0x73, 0x53, 0x8b, 0x0b, 0x12, 0x93, 0x53, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x12, 0x5c, 0xec, 0xc5, 0x20, 0x95, 0x9e, 0x2e,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x30, 0x2e, 0x48, 0x5f, 0x51, 0x6a, 0x41, 0x4e, 0x66,
	0x72, 0xa2, 0xa7, 0x8b, 0x04, 0x33, 0x58, 0x0e, 0x21, 0xa0, 0x24, 0x80, 0x6a, 0x4f, 0x71, 0x01,
	0xc8, 0xe6, 0xa0, 0xd4, 0xdc, 0xfc, 0x32, 0x3a, 0xd8, 0x8c, 0x6c, 0x4f, 0x71, 0x81, 0xd2, 0x0c,
	0x46, 0x2e, 0x9e, 0xe0, 0xca, 0xbc, 0x64, 0xda, 0x5a, 0x2c, 0x24, 0xc5, 0xc5, 0x91, 0x56, 0x94,
	0x9f, 0xeb, 0x97, 0x9f, 0x92, 0x2a, 0xc1, 0x02, 0x36, 0x14, 0xce, 0x17, 0x12, 0xe3, 0x62, 0x2b,
	0xc9, 0x07, 0xcb, 0xb0, 0x82, 0x65, 0xa0, 0x3c, 0x25, 0x3e, 0x64, 0x97, 0x15, 0x17, 0x18, 0xdd,
	0x05, 0x39, 0x15, 0x12, 0x59, 0x8e, 0x29, 0xb9, 0x99, 0x79, 0x42, 0xae, 0x5c, 0xdc, 0x48, 0xe1,
	0x28, 0x24, 0xa9, 0x07, 0x8f, 0x4a, 0x3d, 0xd4, 0x78, 0x94, 0xc2, 0x25, 0x55, 0x5c, 0xa0, 0xc4,
	0x00, 0x32, 0x06, 0x29, 0x50, 0x50, 0x8c, 0x41, 0x8d, 0x14, 0x29, 0x5c, 0x52, 0x60, 0x63, 0xec,
	0xb9, 0x38, 0xe1, 0xce, 0x15, 0x12, 0x47, 0x52, 0x89, 0x1c, 0xbc, 0x52, 0xd8, 0x25, 0x40, 0x06,
	0x24, 0xb1, 0x81, 0x13, 0xa4, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x78, 0x43, 0xfb, 0xa1,
	0x02, 0x00, 0x00,
}
