// Code generated by box-cli. YOU CAN EDIT.

package main

import (
	"flag"
	"github.com/tddhit/box/mw"
	"github.com/tddhit/box/transport"
	"github.com/tddhit/tools/log"
	. "github.com/tddhit/xsearch/searchd/conf"
	"github.com/tddhit/xsearch/searchd/searchdpb"
	"github.com/tddhit/xsearch/searchd/service"
)

var (
	confPath        string
	clientGRPCAddr  string
	clusterGRPCAddr string
)

func init() {
	flag.StringVar(&confPath, "conf-path", "conf/searchd.yml", "config file")
	flag.StringVar(&clientGRPCAddr, "client-grpc-addr", "grpc://127.0.0.1:9000", "process client request")
	flag.StringVar(&clusterGRPCAddr, "cluster-grpc-addr", "grpc://127.0.0.1:9001", "process cluster request")
	flag.Parse()
}

func main() {
	var (
		conf Conf
		err  error
		svc  interface{}
	)
	NewConf(confPath, &conf)
	log.Init(conf.LogPath, conf.LogLevel)
	if mw.IsWorker() {
		svc = service.NewService()
	}

	// new GRPC Server
	grpcServer, err := transport.Listen(grpcAddr)
	if err != nil {
		log.Fatal(err)
	}
	if mw.IsWorker() {
		grpcServer.Register(searchdpb.SearchdGrpcServiceDesc, svc)
	}

	// run with master-worker
	mw.Run(mw.WithServer(grpcServer))
}
