// Code generated by box-cli. YOU CAN EDIT.

package main

import (
	"flag"

	"github.com/tddhit/box/mw"
	"github.com/tddhit/box/transport"
	"github.com/tddhit/tools/log"

	proxypb "github.com/tddhit/xsearch/proxy/pb"
	"github.com/tddhit/xsearch/proxy/service"
)

var (
	httpAddr   string
	metadAddr  string
	namespaces string
	pidPath    string
	logPath    string
	logLevel   int
)

func init() {
	flag.StringVar(&httpAddr, "http-addr", "http://:10000",
		"client communication address")
	flag.StringVar(&metadAddr, "metad-addr", "grpc://:10010",
		"metad communication address")
	flag.StringVar(&namespaces, "namespaces", "faq,news",
		"Business name separated by a comma")
	flag.StringVar(&pidPath, "pidpath", "/var/proxy.pid", "pid path")
	flag.StringVar(&logPath, "logpath", "", "log file path")
	flag.IntVar(&logLevel, "loglevel", 1,
		"log level (Trace:1, Debug:2, Info:3, Error:5)")
	flag.Parse()
}

func main() {
	log.Init(logPath, logLevel)
	svc, err := service.NewService(metadAddr, namespaces)
	if err != nil {
		log.Fatal(err)
	}
	httpServer, err := transport.Listen(httpAddr)
	if err != nil {
		log.Fatal(err)
	}
	httpServer.Register(proxypb.ProxyHttpServiceDesc, svc)
	mw.Run(mw.WithServer(httpServer))
}
