// Code generated by protoc-gen-box. DO NOT EDIT.
// source: xsearch.proto

package xsearchpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PluginType int32

const (
	PluginType_ANALYSIS PluginType = 0
	PluginType_RERANK   PluginType = 1
)

var PluginType_name = map[int32]string{
	0: "ANALYSIS",
	1: "RERANK",
}
var PluginType_value = map[string]int32{
	"ANALYSIS": 0,
	"RERANK":   1,
}

func (x PluginType) String() string {
	return proto.EnumName(PluginType_name, int32(x))
}
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_xsearch_ad766399b435ba08, []int{0}
}

type Command_Type int32

const (
	Command_INDEX  Command_Type = 0
	Command_REMOVE Command_Type = 1
)

var Command_Type_name = map[int32]string{
	0: "INDEX",
	1: "REMOVE",
}
var Command_Type_value = map[string]int32{
	"INDEX":  0,
	"REMOVE": 1,
}

func (x Command_Type) String() string {
	return proto.EnumName(Command_Type_name, int32(x))
}
func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_xsearch_ad766399b435ba08, []int{3, 0}
}

type Token struct {
	Term                 string   `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsearch_ad766399b435ba08, []int{0}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

type Query struct {
	Raw                  string   `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Tokens               []*Token `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsearch_ad766399b435ba08, []int{1}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (dst *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(dst, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

func (m *Query) GetTokens() []*Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type Document struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tokens               []*Token `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	BM25Score            float32  `protobuf:"fixed32,4,opt,name=BM25Score,proto3" json:"BM25Score,omitempty"`
	SimNetScore          float32  `protobuf:"fixed32,5,opt,name=SimNetScore,proto3" json:"SimNetScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsearch_ad766399b435ba08, []int{2}
}
func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (dst *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(dst, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Document) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Document) GetTokens() []*Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *Document) GetBM25Score() float32 {
	if m != nil {
		return m.BM25Score
	}
	return 0
}

func (m *Document) GetSimNetScore() float32 {
	if m != nil {
		return m.SimNetScore
	}
	return 0
}

type Command struct {
	Type Command_Type `protobuf:"varint,1,opt,name=type,proto3,enum=xsearchpb.Command_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to DocOneof:
	//	*Command_Doc
	//	*Command_DocID
	DocOneof             isCommand_DocOneof `protobuf_oneof:"doc_oneof"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsearch_ad766399b435ba08, []int{3}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

type isCommand_DocOneof interface {
	isCommand_DocOneof()
}

type Command_Doc struct {
	Doc *Document `protobuf:"bytes,2,opt,name=doc,proto3,oneof"`
}
type Command_DocID struct {
	DocID string `protobuf:"bytes,3,opt,name=docID,proto3,oneof"`
}

func (*Command_Doc) isCommand_DocOneof()   {}
func (*Command_DocID) isCommand_DocOneof() {}

func (m *Command) GetDocOneof() isCommand_DocOneof {
	if m != nil {
		return m.DocOneof
	}
	return nil
}

func (m *Command) GetType() Command_Type {
	if m != nil {
		return m.Type
	}
	return Command_INDEX
}

func (m *Command) GetDoc() *Document {
	if x, ok := m.GetDocOneof().(*Command_Doc); ok {
		return x.Doc
	}
	return nil
}

func (m *Command) GetDocID() string {
	if x, ok := m.GetDocOneof().(*Command_DocID); ok {
		return x.DocID
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Command) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Command_OneofMarshaler, _Command_OneofUnmarshaler, _Command_OneofSizer, []interface{}{
		(*Command_Doc)(nil),
		(*Command_DocID)(nil),
	}
}

func _Command_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Command)
	// doc_oneof
	switch x := m.DocOneof.(type) {
	case *Command_Doc:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Doc); err != nil {
			return err
		}
	case *Command_DocID:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.DocID)
	case nil:
	default:
		return fmt.Errorf("Command.DocOneof has unexpected type %T", x)
	}
	return nil
}

func _Command_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Command)
	switch tag {
	case 2: // doc_oneof.doc
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Document)
		err := b.DecodeMessage(msg)
		m.DocOneof = &Command_Doc{msg}
		return true, err
	case 3: // doc_oneof.docID
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.DocOneof = &Command_DocID{x}
		return true, err
	default:
		return false, nil
	}
}

func _Command_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Command)
	// doc_oneof
	switch x := m.DocOneof.(type) {
	case *Command_Doc:
		s := proto.Size(x.Doc)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Command_DocID:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.DocID)))
		n += len(x.DocID)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type QueryAnalysisArgs struct {
	Queries              []*Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAnalysisArgs) Reset()         { *m = QueryAnalysisArgs{} }
func (m *QueryAnalysisArgs) String() string { return proto.CompactTextString(m) }
func (*QueryAnalysisArgs) ProtoMessage()    {}
func (*QueryAnalysisArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsearch_ad766399b435ba08, []int{4}
}
func (m *QueryAnalysisArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAnalysisArgs.Unmarshal(m, b)
}
func (m *QueryAnalysisArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAnalysisArgs.Marshal(b, m, deterministic)
}
func (dst *QueryAnalysisArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAnalysisArgs.Merge(dst, src)
}
func (m *QueryAnalysisArgs) XXX_Size() int {
	return xxx_messageInfo_QueryAnalysisArgs.Size(m)
}
func (m *QueryAnalysisArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAnalysisArgs.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAnalysisArgs proto.InternalMessageInfo

func (m *QueryAnalysisArgs) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

type RerankArgs struct {
	Query                *Query      `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Docs                 []*Document `protobuf:"bytes,2,rep,name=docs,proto3" json:"docs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RerankArgs) Reset()         { *m = RerankArgs{} }
func (m *RerankArgs) String() string { return proto.CompactTextString(m) }
func (*RerankArgs) ProtoMessage()    {}
func (*RerankArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsearch_ad766399b435ba08, []int{5}
}
func (m *RerankArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RerankArgs.Unmarshal(m, b)
}
func (m *RerankArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RerankArgs.Marshal(b, m, deterministic)
}
func (dst *RerankArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RerankArgs.Merge(dst, src)
}
func (m *RerankArgs) XXX_Size() int {
	return xxx_messageInfo_RerankArgs.Size(m)
}
func (m *RerankArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RerankArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RerankArgs proto.InternalMessageInfo

func (m *RerankArgs) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *RerankArgs) GetDocs() []*Document {
	if m != nil {
		return m.Docs
	}
	return nil
}

func init() {
	proto.RegisterType((*Token)(nil), "xsearchpb.Token")
	proto.RegisterType((*Query)(nil), "xsearchpb.Query")
	proto.RegisterType((*Document)(nil), "xsearchpb.Document")
	proto.RegisterType((*Command)(nil), "xsearchpb.Command")
	proto.RegisterType((*QueryAnalysisArgs)(nil), "xsearchpb.QueryAnalysisArgs")
	proto.RegisterType((*RerankArgs)(nil), "xsearchpb.RerankArgs")
	proto.RegisterEnum("xsearchpb.PluginType", PluginType_name, PluginType_value)
	proto.RegisterEnum("xsearchpb.Command_Type", Command_Type_name, Command_Type_value)
}

func init() { proto.RegisterFile("xsearch.proto", fileDescriptor_xsearch_ad766399b435ba08) }

var fileDescriptor_xsearch_ad766399b435ba08 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xdf, 0x6b, 0xd4, 0x40,
	0x10, 0xbe, 0xcd, 0x8f, 0xbb, 0x66, 0x4e, 0x4b, 0x1c, 0x41, 0x03, 0x2a, 0x1c, 0x79, 0x68, 0x8f,
	0x0a, 0xf7, 0x70, 0xe2, 0xb3, 0xa4, 0xcd, 0x41, 0x83, 0xf6, 0xd4, 0x4d, 0x11, 0x7d, 0x10, 0x49,
	0x37, 0x6b, 0x0d, 0x6d, 0x76, 0xe3, 0x66, 0x83, 0xe6, 0x9f, 0xf1, 0xc5, 0x7f, 0x54, 0xb2, 0x97,
	0x68, 0xc0, 0xa3, 0x6f, 0x33, 0xf3, 0x7d, 0xf3, 0xcd, 0x7c, 0x3b, 0x0b, 0xf7, 0x7f, 0xd6, 0x3c,
	0x53, 0xec, 0xdb, 0xaa, 0x52, 0x52, 0x4b, 0xf4, 0xfa, 0xb4, 0xba, 0x0a, 0x9f, 0x80, 0x7b, 0x29,
	0x6f, 0xb8, 0x40, 0x04, 0x47, 0x73, 0x55, 0x06, 0x64, 0x41, 0x96, 0x1e, 0x35, 0x71, 0x78, 0x06,
	0xee, 0xfb, 0x86, 0xab, 0x16, 0x7d, 0xb0, 0x55, 0xf6, 0xa3, 0xc7, 0xba, 0x10, 0x97, 0x30, 0xd5,
	0x5d, 0x5f, 0x1d, 0x58, 0x0b, 0x7b, 0x39, 0x5f, 0xfb, 0xab, 0xbf, 0x9a, 0x2b, 0x23, 0x48, 0x7b,
	0x3c, 0xfc, 0x45, 0xe0, 0x20, 0x96, 0xac, 0x29, 0xb9, 0xd0, 0x78, 0x08, 0x56, 0x12, 0xf7, 0x3a,
	0x56, 0x12, 0x63, 0x00, 0x33, 0x26, 0x85, 0xe6, 0x42, 0x07, 0x96, 0x29, 0x0e, 0xe9, 0x68, 0x80,
	0x7d, 0xf7, 0x00, 0x7c, 0x0a, 0xde, 0xe9, 0xc5, 0xfa, 0x65, 0xca, 0xa4, 0xe2, 0x81, 0xb3, 0x20,
	0x4b, 0x8b, 0xfe, 0x2b, 0xe0, 0x02, 0xe6, 0x69, 0x51, 0x6e, 0xb9, 0xde, 0xe1, 0xae, 0xc1, 0xc7,
	0xa5, 0xf0, 0x37, 0x81, 0xd9, 0x99, 0x2c, 0xcb, 0x4c, 0xe4, 0xf8, 0x1c, 0x1c, 0xdd, 0x56, 0xdc,
	0x6c, 0x78, 0xb8, 0x7e, 0x3c, 0x9a, 0xd9, 0x33, 0x56, 0x97, 0x6d, 0xc5, 0xa9, 0x21, 0xe1, 0x31,
	0xd8, 0xb9, 0x64, 0x66, 0xf1, 0xf9, 0xfa, 0xe1, 0x88, 0x3b, 0xd8, 0x3d, 0x9f, 0xd0, 0x8e, 0x81,
	0x8f, 0xc0, 0xcd, 0x25, 0x4b, 0xe2, 0xc0, 0xee, 0x3c, 0x9e, 0x4f, 0xe8, 0x2e, 0x0d, 0x9f, 0x81,
	0xd3, 0xc9, 0xa1, 0x07, 0x6e, 0xb2, 0x8d, 0x37, 0x1f, 0xfd, 0x09, 0x02, 0x4c, 0xe9, 0xe6, 0xe2,
	0xed, 0x87, 0x8d, 0x4f, 0x4e, 0xe7, 0xe0, 0xe5, 0x92, 0x7d, 0x91, 0x82, 0xcb, 0xaf, 0xe1, 0x2b,
	0x78, 0x60, 0x6e, 0x11, 0x89, 0xec, 0xb6, 0xad, 0x8b, 0x3a, 0x52, 0xd7, 0x35, 0x9e, 0xc0, 0xec,
	0x7b, 0xc3, 0x55, 0xc1, 0xeb, 0x80, 0xfc, 0xf7, 0x4a, 0x86, 0x4e, 0x07, 0x42, 0xf8, 0x19, 0x80,
	0x72, 0x95, 0x89, 0x1b, 0xd3, 0x79, 0x04, 0x6e, 0x07, 0xb4, 0xc6, 0xe9, 0xbe, 0xbe, 0x1d, 0x8c,
	0xc7, 0xe0, 0xe4, 0x92, 0x0d, 0x57, 0xde, 0x67, 0x92, 0x1a, 0xc2, 0xc9, 0x11, 0xc0, 0xbb, 0xdb,
	0xe6, 0xba, 0x10, 0xc6, 0xd1, 0x3d, 0x38, 0x88, 0xb6, 0xd1, 0x9b, 0x4f, 0x69, 0x92, 0x0e, 0xa6,
	0x68, 0xb4, 0x7d, 0xed, 0x93, 0xab, 0xa9, 0xf9, 0x82, 0x2f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x69, 0x80, 0x1c, 0x57, 0x93, 0x02, 0x00, 0x00,
}
