// Code generated by protoc-gen-box. DO NOT EDIT.
// source: metad.proto

package metadpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	tr "github.com/tddhit/box/transport"
	tropt "github.com/tddhit/box/transport/option"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import (
	context1 "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterNodeReq_Type int32

const (
	RegisterNodeReq_RegisterShard   RegisterNodeReq_Type = 0
	RegisterNodeReq_UnregisterShard RegisterNodeReq_Type = 1
	RegisterNodeReq_Heartbeat       RegisterNodeReq_Type = 2
)

var RegisterNodeReq_Type_name = map[int32]string{
	0: "RegisterShard",
	1: "UnregisterShard",
	2: "Heartbeat",
}
var RegisterNodeReq_Type_value = map[string]int32{
	"RegisterShard":   0,
	"UnregisterShard": 1,
	"Heartbeat":       2,
}

func (x RegisterNodeReq_Type) String() string {
	return proto.EnumName(RegisterNodeReq_Type_name, int32(x))
}
func (RegisterNodeReq_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{2, 0}
}

type RegisterNodeRsp_Type int32

const (
	RegisterNodeRsp_CreateShard RegisterNodeRsp_Type = 0
	RegisterNodeRsp_RemoveShard RegisterNodeRsp_Type = 1
)

var RegisterNodeRsp_Type_name = map[int32]string{
	0: "CreateShard",
	1: "RemoveShard",
}
var RegisterNodeRsp_Type_value = map[string]int32{
	"CreateShard": 0,
	"RemoveShard": 1,
}

func (x RegisterNodeRsp_Type) String() string {
	return proto.EnumName(RegisterNodeRsp_Type_name, int32(x))
}
func (RegisterNodeRsp_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{3, 0}
}

type RegisterClientReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterClientReq) Reset()         { *m = RegisterClientReq{} }
func (m *RegisterClientReq) String() string { return proto.CompactTextString(m) }
func (*RegisterClientReq) ProtoMessage()    {}
func (*RegisterClientReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{0}
}
func (m *RegisterClientReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterClientReq.Unmarshal(m, b)
}
func (m *RegisterClientReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterClientReq.Marshal(b, m, deterministic)
}
func (dst *RegisterClientReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterClientReq.Merge(dst, src)
}
func (m *RegisterClientReq) XXX_Size() int {
	return xxx_messageInfo_RegisterClientReq.Size(m)
}
func (m *RegisterClientReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterClientReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterClientReq proto.InternalMessageInfo

func (m *RegisterClientReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type RegisterClientRsp struct {
	Table                *Metadata `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterClientRsp) Reset()         { *m = RegisterClientRsp{} }
func (m *RegisterClientRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterClientRsp) ProtoMessage()    {}
func (*RegisterClientRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{1}
}
func (m *RegisterClientRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterClientRsp.Unmarshal(m, b)
}
func (m *RegisterClientRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterClientRsp.Marshal(b, m, deterministic)
}
func (dst *RegisterClientRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterClientRsp.Merge(dst, src)
}
func (m *RegisterClientRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterClientRsp.Size(m)
}
func (m *RegisterClientRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterClientRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterClientRsp proto.InternalMessageInfo

func (m *RegisterClientRsp) GetTable() *Metadata {
	if m != nil {
		return m.Table
	}
	return nil
}

type RegisterNodeReq struct {
	Type                 RegisterNodeReq_Type `protobuf:"varint,1,opt,name=type,proto3,enum=metadpb.RegisterNodeReq_Type" json:"type,omitempty"`
	Addr                 string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Namespace            string               `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	GroupID              uint32               `protobuf:"varint,4,opt,name=groupID,proto3" json:"groupID,omitempty"`
	ReplicaID            uint32               `protobuf:"varint,5,opt,name=replicaID,proto3" json:"replicaID,omitempty"`
	TodoID               uint32               `protobuf:"varint,6,opt,name=todoID,proto3" json:"todoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisterNodeReq) Reset()         { *m = RegisterNodeReq{} }
func (m *RegisterNodeReq) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeReq) ProtoMessage()    {}
func (*RegisterNodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{2}
}
func (m *RegisterNodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeReq.Unmarshal(m, b)
}
func (m *RegisterNodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeReq.Marshal(b, m, deterministic)
}
func (dst *RegisterNodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeReq.Merge(dst, src)
}
func (m *RegisterNodeReq) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeReq.Size(m)
}
func (m *RegisterNodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeReq proto.InternalMessageInfo

func (m *RegisterNodeReq) GetType() RegisterNodeReq_Type {
	if m != nil {
		return m.Type
	}
	return RegisterNodeReq_RegisterShard
}

func (m *RegisterNodeReq) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *RegisterNodeReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *RegisterNodeReq) GetGroupID() uint32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *RegisterNodeReq) GetReplicaID() uint32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

func (m *RegisterNodeReq) GetTodoID() uint32 {
	if m != nil {
		return m.TodoID
	}
	return 0
}

type RegisterNodeRsp struct {
	Type                 RegisterNodeRsp_Type `protobuf:"varint,1,opt,name=type,proto3,enum=metadpb.RegisterNodeRsp_Type" json:"type,omitempty"`
	ShardID              string               `protobuf:"bytes,2,opt,name=shardID,proto3" json:"shardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisterNodeRsp) Reset()         { *m = RegisterNodeRsp{} }
func (m *RegisterNodeRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeRsp) ProtoMessage()    {}
func (*RegisterNodeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{3}
}
func (m *RegisterNodeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeRsp.Unmarshal(m, b)
}
func (m *RegisterNodeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeRsp.Marshal(b, m, deterministic)
}
func (dst *RegisterNodeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeRsp.Merge(dst, src)
}
func (m *RegisterNodeRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeRsp.Size(m)
}
func (m *RegisterNodeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeRsp proto.InternalMessageInfo

func (m *RegisterNodeRsp) GetType() RegisterNodeRsp_Type {
	if m != nil {
		return m.Type
	}
	return RegisterNodeRsp_CreateShard
}

func (m *RegisterNodeRsp) GetShardID() string {
	if m != nil {
		return m.ShardID
	}
	return ""
}

type CreateNamespaceReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ShardNum             uint32   `protobuf:"varint,2,opt,name=shardNum,proto3" json:"shardNum,omitempty"`
	ReplicaFactor        uint32   `protobuf:"varint,3,opt,name=replicaFactor,proto3" json:"replicaFactor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceReq) Reset()         { *m = CreateNamespaceReq{} }
func (m *CreateNamespaceReq) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceReq) ProtoMessage()    {}
func (*CreateNamespaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{4}
}
func (m *CreateNamespaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceReq.Unmarshal(m, b)
}
func (m *CreateNamespaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceReq.Marshal(b, m, deterministic)
}
func (dst *CreateNamespaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceReq.Merge(dst, src)
}
func (m *CreateNamespaceReq) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceReq.Size(m)
}
func (m *CreateNamespaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceReq proto.InternalMessageInfo

func (m *CreateNamespaceReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateNamespaceReq) GetShardNum() uint32 {
	if m != nil {
		return m.ShardNum
	}
	return 0
}

func (m *CreateNamespaceReq) GetReplicaFactor() uint32 {
	if m != nil {
		return m.ReplicaFactor
	}
	return 0
}

type CreateNamespaceRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceRsp) Reset()         { *m = CreateNamespaceRsp{} }
func (m *CreateNamespaceRsp) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRsp) ProtoMessage()    {}
func (*CreateNamespaceRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{5}
}
func (m *CreateNamespaceRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRsp.Unmarshal(m, b)
}
func (m *CreateNamespaceRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRsp.Marshal(b, m, deterministic)
}
func (dst *CreateNamespaceRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRsp.Merge(dst, src)
}
func (m *CreateNamespaceRsp) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRsp.Size(m)
}
func (m *CreateNamespaceRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRsp proto.InternalMessageInfo

type DropNamespaceReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropNamespaceReq) Reset()         { *m = DropNamespaceReq{} }
func (m *DropNamespaceReq) String() string { return proto.CompactTextString(m) }
func (*DropNamespaceReq) ProtoMessage()    {}
func (*DropNamespaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{6}
}
func (m *DropNamespaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropNamespaceReq.Unmarshal(m, b)
}
func (m *DropNamespaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropNamespaceReq.Marshal(b, m, deterministic)
}
func (dst *DropNamespaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropNamespaceReq.Merge(dst, src)
}
func (m *DropNamespaceReq) XXX_Size() int {
	return xxx_messageInfo_DropNamespaceReq.Size(m)
}
func (m *DropNamespaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DropNamespaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_DropNamespaceReq proto.InternalMessageInfo

func (m *DropNamespaceReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type DropNamespaceRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropNamespaceRsp) Reset()         { *m = DropNamespaceRsp{} }
func (m *DropNamespaceRsp) String() string { return proto.CompactTextString(m) }
func (*DropNamespaceRsp) ProtoMessage()    {}
func (*DropNamespaceRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{7}
}
func (m *DropNamespaceRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropNamespaceRsp.Unmarshal(m, b)
}
func (m *DropNamespaceRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropNamespaceRsp.Marshal(b, m, deterministic)
}
func (dst *DropNamespaceRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropNamespaceRsp.Merge(dst, src)
}
func (m *DropNamespaceRsp) XXX_Size() int {
	return xxx_messageInfo_DropNamespaceRsp.Size(m)
}
func (m *DropNamespaceRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DropNamespaceRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DropNamespaceRsp proto.InternalMessageInfo

type AddNodeToNamespaceReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	AdminAddr            string   `protobuf:"bytes,3,opt,name=adminAddr,proto3" json:"adminAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeToNamespaceReq) Reset()         { *m = AddNodeToNamespaceReq{} }
func (m *AddNodeToNamespaceReq) String() string { return proto.CompactTextString(m) }
func (*AddNodeToNamespaceReq) ProtoMessage()    {}
func (*AddNodeToNamespaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{8}
}
func (m *AddNodeToNamespaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeToNamespaceReq.Unmarshal(m, b)
}
func (m *AddNodeToNamespaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeToNamespaceReq.Marshal(b, m, deterministic)
}
func (dst *AddNodeToNamespaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeToNamespaceReq.Merge(dst, src)
}
func (m *AddNodeToNamespaceReq) XXX_Size() int {
	return xxx_messageInfo_AddNodeToNamespaceReq.Size(m)
}
func (m *AddNodeToNamespaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeToNamespaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeToNamespaceReq proto.InternalMessageInfo

func (m *AddNodeToNamespaceReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AddNodeToNamespaceReq) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *AddNodeToNamespaceReq) GetAdminAddr() string {
	if m != nil {
		return m.AdminAddr
	}
	return ""
}

type AddNodeToNamespaceRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeToNamespaceRsp) Reset()         { *m = AddNodeToNamespaceRsp{} }
func (m *AddNodeToNamespaceRsp) String() string { return proto.CompactTextString(m) }
func (*AddNodeToNamespaceRsp) ProtoMessage()    {}
func (*AddNodeToNamespaceRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{9}
}
func (m *AddNodeToNamespaceRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeToNamespaceRsp.Unmarshal(m, b)
}
func (m *AddNodeToNamespaceRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeToNamespaceRsp.Marshal(b, m, deterministic)
}
func (dst *AddNodeToNamespaceRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeToNamespaceRsp.Merge(dst, src)
}
func (m *AddNodeToNamespaceRsp) XXX_Size() int {
	return xxx_messageInfo_AddNodeToNamespaceRsp.Size(m)
}
func (m *AddNodeToNamespaceRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeToNamespaceRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeToNamespaceRsp proto.InternalMessageInfo

type RemoveNodeFromNamespaceReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeFromNamespaceReq) Reset()         { *m = RemoveNodeFromNamespaceReq{} }
func (m *RemoveNodeFromNamespaceReq) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeFromNamespaceReq) ProtoMessage()    {}
func (*RemoveNodeFromNamespaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{10}
}
func (m *RemoveNodeFromNamespaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeFromNamespaceReq.Unmarshal(m, b)
}
func (m *RemoveNodeFromNamespaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeFromNamespaceReq.Marshal(b, m, deterministic)
}
func (dst *RemoveNodeFromNamespaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeFromNamespaceReq.Merge(dst, src)
}
func (m *RemoveNodeFromNamespaceReq) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeFromNamespaceReq.Size(m)
}
func (m *RemoveNodeFromNamespaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeFromNamespaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeFromNamespaceReq proto.InternalMessageInfo

func (m *RemoveNodeFromNamespaceReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *RemoveNodeFromNamespaceReq) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type RemoveNodeFromNamespaceRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeFromNamespaceRsp) Reset()         { *m = RemoveNodeFromNamespaceRsp{} }
func (m *RemoveNodeFromNamespaceRsp) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeFromNamespaceRsp) ProtoMessage()    {}
func (*RemoveNodeFromNamespaceRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{11}
}
func (m *RemoveNodeFromNamespaceRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeFromNamespaceRsp.Unmarshal(m, b)
}
func (m *RemoveNodeFromNamespaceRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeFromNamespaceRsp.Marshal(b, m, deterministic)
}
func (dst *RemoveNodeFromNamespaceRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeFromNamespaceRsp.Merge(dst, src)
}
func (m *RemoveNodeFromNamespaceRsp) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeFromNamespaceRsp.Size(m)
}
func (m *RemoveNodeFromNamespaceRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeFromNamespaceRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeFromNamespaceRsp proto.InternalMessageInfo

type ReplaceNodeInNamespaceReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	OldAddr              string   `protobuf:"bytes,2,opt,name=oldAddr,proto3" json:"oldAddr,omitempty"`
	NewAddr              string   `protobuf:"bytes,3,opt,name=newAddr,proto3" json:"newAddr,omitempty"`
	NewAdminAddr         string   `protobuf:"bytes,4,opt,name=newAdminAddr,proto3" json:"newAdminAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceNodeInNamespaceReq) Reset()         { *m = ReplaceNodeInNamespaceReq{} }
func (m *ReplaceNodeInNamespaceReq) String() string { return proto.CompactTextString(m) }
func (*ReplaceNodeInNamespaceReq) ProtoMessage()    {}
func (*ReplaceNodeInNamespaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{12}
}
func (m *ReplaceNodeInNamespaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceNodeInNamespaceReq.Unmarshal(m, b)
}
func (m *ReplaceNodeInNamespaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceNodeInNamespaceReq.Marshal(b, m, deterministic)
}
func (dst *ReplaceNodeInNamespaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceNodeInNamespaceReq.Merge(dst, src)
}
func (m *ReplaceNodeInNamespaceReq) XXX_Size() int {
	return xxx_messageInfo_ReplaceNodeInNamespaceReq.Size(m)
}
func (m *ReplaceNodeInNamespaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceNodeInNamespaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceNodeInNamespaceReq proto.InternalMessageInfo

func (m *ReplaceNodeInNamespaceReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ReplaceNodeInNamespaceReq) GetOldAddr() string {
	if m != nil {
		return m.OldAddr
	}
	return ""
}

func (m *ReplaceNodeInNamespaceReq) GetNewAddr() string {
	if m != nil {
		return m.NewAddr
	}
	return ""
}

func (m *ReplaceNodeInNamespaceReq) GetNewAdminAddr() string {
	if m != nil {
		return m.NewAdminAddr
	}
	return ""
}

type ReplaceNodeInNamespaceRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceNodeInNamespaceRsp) Reset()         { *m = ReplaceNodeInNamespaceRsp{} }
func (m *ReplaceNodeInNamespaceRsp) String() string { return proto.CompactTextString(m) }
func (*ReplaceNodeInNamespaceRsp) ProtoMessage()    {}
func (*ReplaceNodeInNamespaceRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{13}
}
func (m *ReplaceNodeInNamespaceRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceNodeInNamespaceRsp.Unmarshal(m, b)
}
func (m *ReplaceNodeInNamespaceRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceNodeInNamespaceRsp.Marshal(b, m, deterministic)
}
func (dst *ReplaceNodeInNamespaceRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceNodeInNamespaceRsp.Merge(dst, src)
}
func (m *ReplaceNodeInNamespaceRsp) XXX_Size() int {
	return xxx_messageInfo_ReplaceNodeInNamespaceRsp.Size(m)
}
func (m *ReplaceNodeInNamespaceRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceNodeInNamespaceRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceNodeInNamespaceRsp proto.InternalMessageInfo

type AutoBalanceReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoBalanceReq) Reset()         { *m = AutoBalanceReq{} }
func (m *AutoBalanceReq) String() string { return proto.CompactTextString(m) }
func (*AutoBalanceReq) ProtoMessage()    {}
func (*AutoBalanceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{14}
}
func (m *AutoBalanceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoBalanceReq.Unmarshal(m, b)
}
func (m *AutoBalanceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoBalanceReq.Marshal(b, m, deterministic)
}
func (dst *AutoBalanceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoBalanceReq.Merge(dst, src)
}
func (m *AutoBalanceReq) XXX_Size() int {
	return xxx_messageInfo_AutoBalanceReq.Size(m)
}
func (m *AutoBalanceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoBalanceReq.DiscardUnknown(m)
}

var xxx_messageInfo_AutoBalanceReq proto.InternalMessageInfo

func (m *AutoBalanceReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type AutoBalanceRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoBalanceRsp) Reset()         { *m = AutoBalanceRsp{} }
func (m *AutoBalanceRsp) String() string { return proto.CompactTextString(m) }
func (*AutoBalanceRsp) ProtoMessage()    {}
func (*AutoBalanceRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{15}
}
func (m *AutoBalanceRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoBalanceRsp.Unmarshal(m, b)
}
func (m *AutoBalanceRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoBalanceRsp.Marshal(b, m, deterministic)
}
func (dst *AutoBalanceRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoBalanceRsp.Merge(dst, src)
}
func (m *AutoBalanceRsp) XXX_Size() int {
	return xxx_messageInfo_AutoBalanceRsp.Size(m)
}
func (m *AutoBalanceRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoBalanceRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AutoBalanceRsp proto.InternalMessageInfo

type MigrateShardReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ShardID              uint32   `protobuf:"varint,2,opt,name=shardID,proto3" json:"shardID,omitempty"`
	ReplicaID            uint32   `protobuf:"varint,3,opt,name=replicaID,proto3" json:"replicaID,omitempty"`
	FromNode             string   `protobuf:"bytes,4,opt,name=fromNode,proto3" json:"fromNode,omitempty"`
	ToNode               string   `protobuf:"bytes,5,opt,name=toNode,proto3" json:"toNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateShardReq) Reset()         { *m = MigrateShardReq{} }
func (m *MigrateShardReq) String() string { return proto.CompactTextString(m) }
func (*MigrateShardReq) ProtoMessage()    {}
func (*MigrateShardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{16}
}
func (m *MigrateShardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateShardReq.Unmarshal(m, b)
}
func (m *MigrateShardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateShardReq.Marshal(b, m, deterministic)
}
func (dst *MigrateShardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateShardReq.Merge(dst, src)
}
func (m *MigrateShardReq) XXX_Size() int {
	return xxx_messageInfo_MigrateShardReq.Size(m)
}
func (m *MigrateShardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateShardReq.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateShardReq proto.InternalMessageInfo

func (m *MigrateShardReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *MigrateShardReq) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *MigrateShardReq) GetReplicaID() uint32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

func (m *MigrateShardReq) GetFromNode() string {
	if m != nil {
		return m.FromNode
	}
	return ""
}

func (m *MigrateShardReq) GetToNode() string {
	if m != nil {
		return m.ToNode
	}
	return ""
}

type MigrateShardRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateShardRsp) Reset()         { *m = MigrateShardRsp{} }
func (m *MigrateShardRsp) String() string { return proto.CompactTextString(m) }
func (*MigrateShardRsp) ProtoMessage()    {}
func (*MigrateShardRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{17}
}
func (m *MigrateShardRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateShardRsp.Unmarshal(m, b)
}
func (m *MigrateShardRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateShardRsp.Marshal(b, m, deterministic)
}
func (dst *MigrateShardRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateShardRsp.Merge(dst, src)
}
func (m *MigrateShardRsp) XXX_Size() int {
	return xxx_messageInfo_MigrateShardRsp.Size(m)
}
func (m *MigrateShardRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateShardRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateShardRsp proto.InternalMessageInfo

type InfoReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoReq) Reset()         { *m = InfoReq{} }
func (m *InfoReq) String() string { return proto.CompactTextString(m) }
func (*InfoReq) ProtoMessage()    {}
func (*InfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{18}
}
func (m *InfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoReq.Unmarshal(m, b)
}
func (m *InfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoReq.Marshal(b, m, deterministic)
}
func (dst *InfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoReq.Merge(dst, src)
}
func (m *InfoReq) XXX_Size() int {
	return xxx_messageInfo_InfoReq.Size(m)
}
func (m *InfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoReq proto.InternalMessageInfo

func (m *InfoReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type InfoRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRsp) Reset()         { *m = InfoRsp{} }
func (m *InfoRsp) String() string { return proto.CompactTextString(m) }
func (*InfoRsp) ProtoMessage()    {}
func (*InfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{19}
}
func (m *InfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRsp.Unmarshal(m, b)
}
func (m *InfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRsp.Marshal(b, m, deterministic)
}
func (dst *InfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRsp.Merge(dst, src)
}
func (m *InfoRsp) XXX_Size() int {
	return xxx_messageInfo_InfoRsp.Size(m)
}
func (m *InfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRsp proto.InternalMessageInfo

type CommitReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitReq) Reset()         { *m = CommitReq{} }
func (m *CommitReq) String() string { return proto.CompactTextString(m) }
func (*CommitReq) ProtoMessage()    {}
func (*CommitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{20}
}
func (m *CommitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitReq.Unmarshal(m, b)
}
func (m *CommitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitReq.Marshal(b, m, deterministic)
}
func (dst *CommitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitReq.Merge(dst, src)
}
func (m *CommitReq) XXX_Size() int {
	return xxx_messageInfo_CommitReq.Size(m)
}
func (m *CommitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitReq.DiscardUnknown(m)
}

var xxx_messageInfo_CommitReq proto.InternalMessageInfo

func (m *CommitReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type CommitRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRsp) Reset()         { *m = CommitRsp{} }
func (m *CommitRsp) String() string { return proto.CompactTextString(m) }
func (*CommitRsp) ProtoMessage()    {}
func (*CommitRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{21}
}
func (m *CommitRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRsp.Unmarshal(m, b)
}
func (m *CommitRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRsp.Marshal(b, m, deterministic)
}
func (dst *CommitRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRsp.Merge(dst, src)
}
func (m *CommitRsp) XXX_Size() int {
	return xxx_messageInfo_CommitRsp.Size(m)
}
func (m *CommitRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRsp proto.InternalMessageInfo

type Metadata struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ShardNum             uint32            `protobuf:"varint,2,opt,name=shardNum,proto3" json:"shardNum,omitempty"`
	ReplicaFactor        uint32            `protobuf:"varint,3,opt,name=replicaFactor,proto3" json:"replicaFactor,omitempty"`
	Shards               []*Metadata_Shard `protobuf:"bytes,4,rep,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{22}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Metadata) GetShardNum() uint32 {
	if m != nil {
		return m.ShardNum
	}
	return 0
}

func (m *Metadata) GetReplicaFactor() uint32 {
	if m != nil {
		return m.ReplicaFactor
	}
	return 0
}

func (m *Metadata) GetShards() []*Metadata_Shard {
	if m != nil {
		return m.Shards
	}
	return nil
}

type Metadata_Shard struct {
	GroupID              uint32   `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	ReplicaID            uint32   `protobuf:"varint,2,opt,name=replicaID,proto3" json:"replicaID,omitempty"`
	NodeAddr             string   `protobuf:"bytes,3,opt,name=nodeAddr,proto3" json:"nodeAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata_Shard) Reset()         { *m = Metadata_Shard{} }
func (m *Metadata_Shard) String() string { return proto.CompactTextString(m) }
func (*Metadata_Shard) ProtoMessage()    {}
func (*Metadata_Shard) Descriptor() ([]byte, []int) {
	return fileDescriptor_metad_6f03260f97e5f353, []int{22, 0}
}
func (m *Metadata_Shard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata_Shard.Unmarshal(m, b)
}
func (m *Metadata_Shard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata_Shard.Marshal(b, m, deterministic)
}
func (dst *Metadata_Shard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata_Shard.Merge(dst, src)
}
func (m *Metadata_Shard) XXX_Size() int {
	return xxx_messageInfo_Metadata_Shard.Size(m)
}
func (m *Metadata_Shard) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata_Shard.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata_Shard proto.InternalMessageInfo

func (m *Metadata_Shard) GetGroupID() uint32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *Metadata_Shard) GetReplicaID() uint32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

func (m *Metadata_Shard) GetNodeAddr() string {
	if m != nil {
		return m.NodeAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterClientReq)(nil), "metadpb.RegisterClientReq")
	proto.RegisterType((*RegisterClientRsp)(nil), "metadpb.RegisterClientRsp")
	proto.RegisterType((*RegisterNodeReq)(nil), "metadpb.RegisterNodeReq")
	proto.RegisterType((*RegisterNodeRsp)(nil), "metadpb.RegisterNodeRsp")
	proto.RegisterType((*CreateNamespaceReq)(nil), "metadpb.CreateNamespaceReq")
	proto.RegisterType((*CreateNamespaceRsp)(nil), "metadpb.CreateNamespaceRsp")
	proto.RegisterType((*DropNamespaceReq)(nil), "metadpb.DropNamespaceReq")
	proto.RegisterType((*DropNamespaceRsp)(nil), "metadpb.DropNamespaceRsp")
	proto.RegisterType((*AddNodeToNamespaceReq)(nil), "metadpb.AddNodeToNamespaceReq")
	proto.RegisterType((*AddNodeToNamespaceRsp)(nil), "metadpb.AddNodeToNamespaceRsp")
	proto.RegisterType((*RemoveNodeFromNamespaceReq)(nil), "metadpb.RemoveNodeFromNamespaceReq")
	proto.RegisterType((*RemoveNodeFromNamespaceRsp)(nil), "metadpb.RemoveNodeFromNamespaceRsp")
	proto.RegisterType((*ReplaceNodeInNamespaceReq)(nil), "metadpb.ReplaceNodeInNamespaceReq")
	proto.RegisterType((*ReplaceNodeInNamespaceRsp)(nil), "metadpb.ReplaceNodeInNamespaceRsp")
	proto.RegisterType((*AutoBalanceReq)(nil), "metadpb.AutoBalanceReq")
	proto.RegisterType((*AutoBalanceRsp)(nil), "metadpb.AutoBalanceRsp")
	proto.RegisterType((*MigrateShardReq)(nil), "metadpb.MigrateShardReq")
	proto.RegisterType((*MigrateShardRsp)(nil), "metadpb.MigrateShardRsp")
	proto.RegisterType((*InfoReq)(nil), "metadpb.InfoReq")
	proto.RegisterType((*InfoRsp)(nil), "metadpb.InfoRsp")
	proto.RegisterType((*CommitReq)(nil), "metadpb.CommitReq")
	proto.RegisterType((*CommitRsp)(nil), "metadpb.CommitRsp")
	proto.RegisterType((*Metadata)(nil), "metadpb.Metadata")
	proto.RegisterType((*Metadata_Shard)(nil), "metadpb.Metadata.Shard")
	proto.RegisterEnum("metadpb.RegisterNodeReq_Type", RegisterNodeReq_Type_name, RegisterNodeReq_Type_value)
	proto.RegisterEnum("metadpb.RegisterNodeRsp_Type", RegisterNodeRsp_Type_name, RegisterNodeRsp_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ tr.Server
var _ tr.ClientConn
var _ tropt.CallOption

type MetadGrpcClient interface {
	RegisterClient(ctx context.Context, opts ...tropt.CallOption) (Metad_RegisterClientClient, error)
	RegisterNode(ctx context.Context, opts ...tropt.CallOption) (Metad_RegisterNodeClient, error)
	CreateNamespace(ctx context.Context, in *CreateNamespaceReq, opts ...tropt.CallOption) (*CreateNamespaceRsp, error)
	DropNamespace(ctx context.Context, in *DropNamespaceReq, opts ...tropt.CallOption) (*DropNamespaceRsp, error)
	AddNodeToNamespace(ctx context.Context, in *AddNodeToNamespaceReq, opts ...tropt.CallOption) (*AddNodeToNamespaceRsp, error)
	RemoveNodeFromNamespace(ctx context.Context, in *RemoveNodeFromNamespaceReq, opts ...tropt.CallOption) (*RemoveNodeFromNamespaceRsp, error)
	AutoBalance(ctx context.Context, in *AutoBalanceReq, opts ...tropt.CallOption) (*AutoBalanceRsp, error)
	MigrateShard(ctx context.Context, in *MigrateShardReq, opts ...tropt.CallOption) (*MigrateShardRsp, error)
	Info(ctx context.Context, in *InfoReq, opts ...tropt.CallOption) (*InfoRsp, error)
	Commit(ctx context.Context, in *CommitReq, opts ...tropt.CallOption) (*CommitRsp, error)
}

type metadGrpcClient struct {
	cc tr.ClientConn
}

func NewMetadGrpcClient(cc tr.ClientConn) MetadGrpcClient {
	return &metadGrpcClient{cc}
}

func (c *metadGrpcClient) RegisterClient(ctx context.Context, opts ...tropt.CallOption) (Metad_RegisterClientClient, error) {
	stream, err := c.cc.NewStream(ctx, MetadGrpcServiceDesc, 0, "/metadpb.Metad/RegisterClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &metadRegisterClientClient{stream}
	return x, nil
}

func (c *metadGrpcClient) RegisterNode(ctx context.Context, opts ...tropt.CallOption) (Metad_RegisterNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, MetadGrpcServiceDesc, 1, "/metadpb.Metad/RegisterNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &metadRegisterNodeClient{stream}
	return x, nil
}

func (c *metadGrpcClient) CreateNamespace(ctx context.Context, in *CreateNamespaceReq, opts ...tropt.CallOption) (*CreateNamespaceRsp, error) {
	out := new(CreateNamespaceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/CreateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadGrpcClient) DropNamespace(ctx context.Context, in *DropNamespaceReq, opts ...tropt.CallOption) (*DropNamespaceRsp, error) {
	out := new(DropNamespaceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/DropNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadGrpcClient) AddNodeToNamespace(ctx context.Context, in *AddNodeToNamespaceReq, opts ...tropt.CallOption) (*AddNodeToNamespaceRsp, error) {
	out := new(AddNodeToNamespaceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/AddNodeToNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadGrpcClient) RemoveNodeFromNamespace(ctx context.Context, in *RemoveNodeFromNamespaceReq, opts ...tropt.CallOption) (*RemoveNodeFromNamespaceRsp, error) {
	out := new(RemoveNodeFromNamespaceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/RemoveNodeFromNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadGrpcClient) AutoBalance(ctx context.Context, in *AutoBalanceReq, opts ...tropt.CallOption) (*AutoBalanceRsp, error) {
	out := new(AutoBalanceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/AutoBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadGrpcClient) MigrateShard(ctx context.Context, in *MigrateShardReq, opts ...tropt.CallOption) (*MigrateShardRsp, error) {
	out := new(MigrateShardRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/MigrateShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadGrpcClient) Info(ctx context.Context, in *InfoReq, opts ...tropt.CallOption) (*InfoRsp, error) {
	out := new(InfoRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadGrpcClient) Commit(ctx context.Context, in *CommitReq, opts ...tropt.CallOption) (*CommitRsp, error) {
	out := new(CommitRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type metadGrpcServiceDesc struct {
	desc *grpc.ServiceDesc
}

func (d *metadGrpcServiceDesc) Desc() interface{} {
	return d.desc
}

var MetadGrpcServiceDesc = &metadGrpcServiceDesc{&_Metad_serviceDesc}

// Reference imports to suppress errors if they are not otherwise used.
var _ context1.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// MetadClient is the client API for Metad service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadClient interface {
	RegisterClient(ctx context1.Context, opts ...grpc1.CallOption) (Metad_RegisterClientClient, error)
	RegisterNode(ctx context1.Context, opts ...grpc1.CallOption) (Metad_RegisterNodeClient, error)
	CreateNamespace(ctx context1.Context, in *CreateNamespaceReq, opts ...grpc1.CallOption) (*CreateNamespaceRsp, error)
	DropNamespace(ctx context1.Context, in *DropNamespaceReq, opts ...grpc1.CallOption) (*DropNamespaceRsp, error)
	AddNodeToNamespace(ctx context1.Context, in *AddNodeToNamespaceReq, opts ...grpc1.CallOption) (*AddNodeToNamespaceRsp, error)
	RemoveNodeFromNamespace(ctx context1.Context, in *RemoveNodeFromNamespaceReq, opts ...grpc1.CallOption) (*RemoveNodeFromNamespaceRsp, error)
	// rpc ReplaceNodeInNamespace (ReplaceNodeInNamespaceReq) returns (ReplaceNodeInNamespaceRsp) {}
	AutoBalance(ctx context1.Context, in *AutoBalanceReq, opts ...grpc1.CallOption) (*AutoBalanceRsp, error)
	MigrateShard(ctx context1.Context, in *MigrateShardReq, opts ...grpc1.CallOption) (*MigrateShardRsp, error)
	Info(ctx context1.Context, in *InfoReq, opts ...grpc1.CallOption) (*InfoRsp, error)
	Commit(ctx context1.Context, in *CommitReq, opts ...grpc1.CallOption) (*CommitRsp, error)
}

type metadClient struct {
	cc *grpc1.ClientConn
}

func NewMetadClient(cc *grpc1.ClientConn) MetadClient {
	return &metadClient{cc}
}

func (c *metadClient) RegisterClient(ctx context1.Context, opts ...grpc1.CallOption) (Metad_RegisterClientClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Metad_serviceDesc.Streams[0], "/metadpb.Metad/RegisterClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &metadRegisterClientClient{stream}
	return x, nil
}

type Metad_RegisterClientClient interface {
	Send(*RegisterClientReq) error
	Recv() (*RegisterClientRsp, error)
	grpc1.ClientStream
}

type metadRegisterClientClient struct {
	grpc1.ClientStream
}

func (x *metadRegisterClientClient) Send(m *RegisterClientReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metadRegisterClientClient) Recv() (*RegisterClientRsp, error) {
	m := new(RegisterClientRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metadClient) RegisterNode(ctx context1.Context, opts ...grpc1.CallOption) (Metad_RegisterNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Metad_serviceDesc.Streams[1], "/metadpb.Metad/RegisterNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &metadRegisterNodeClient{stream}
	return x, nil
}

type Metad_RegisterNodeClient interface {
	Send(*RegisterNodeReq) error
	Recv() (*RegisterNodeRsp, error)
	grpc1.ClientStream
}

type metadRegisterNodeClient struct {
	grpc1.ClientStream
}

func (x *metadRegisterNodeClient) Send(m *RegisterNodeReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metadRegisterNodeClient) Recv() (*RegisterNodeRsp, error) {
	m := new(RegisterNodeRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metadClient) CreateNamespace(ctx context1.Context, in *CreateNamespaceReq, opts ...grpc1.CallOption) (*CreateNamespaceRsp, error) {
	out := new(CreateNamespaceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/CreateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadClient) DropNamespace(ctx context1.Context, in *DropNamespaceReq, opts ...grpc1.CallOption) (*DropNamespaceRsp, error) {
	out := new(DropNamespaceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/DropNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadClient) AddNodeToNamespace(ctx context1.Context, in *AddNodeToNamespaceReq, opts ...grpc1.CallOption) (*AddNodeToNamespaceRsp, error) {
	out := new(AddNodeToNamespaceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/AddNodeToNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadClient) RemoveNodeFromNamespace(ctx context1.Context, in *RemoveNodeFromNamespaceReq, opts ...grpc1.CallOption) (*RemoveNodeFromNamespaceRsp, error) {
	out := new(RemoveNodeFromNamespaceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/RemoveNodeFromNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadClient) AutoBalance(ctx context1.Context, in *AutoBalanceReq, opts ...grpc1.CallOption) (*AutoBalanceRsp, error) {
	out := new(AutoBalanceRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/AutoBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadClient) MigrateShard(ctx context1.Context, in *MigrateShardReq, opts ...grpc1.CallOption) (*MigrateShardRsp, error) {
	out := new(MigrateShardRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/MigrateShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadClient) Info(ctx context1.Context, in *InfoReq, opts ...grpc1.CallOption) (*InfoRsp, error) {
	out := new(InfoRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadClient) Commit(ctx context1.Context, in *CommitReq, opts ...grpc1.CallOption) (*CommitRsp, error) {
	out := new(CommitRsp)
	err := c.cc.Invoke(ctx, "/metadpb.Metad/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadServer is the server API for Metad service.
type MetadServer interface {
	RegisterClient(Metad_RegisterClientServer) error
	RegisterNode(Metad_RegisterNodeServer) error
	CreateNamespace(context1.Context, *CreateNamespaceReq) (*CreateNamespaceRsp, error)
	DropNamespace(context1.Context, *DropNamespaceReq) (*DropNamespaceRsp, error)
	AddNodeToNamespace(context1.Context, *AddNodeToNamespaceReq) (*AddNodeToNamespaceRsp, error)
	RemoveNodeFromNamespace(context1.Context, *RemoveNodeFromNamespaceReq) (*RemoveNodeFromNamespaceRsp, error)
	// rpc ReplaceNodeInNamespace (ReplaceNodeInNamespaceReq) returns (ReplaceNodeInNamespaceRsp) {}
	AutoBalance(context1.Context, *AutoBalanceReq) (*AutoBalanceRsp, error)
	MigrateShard(context1.Context, *MigrateShardReq) (*MigrateShardRsp, error)
	Info(context1.Context, *InfoReq) (*InfoRsp, error)
	Commit(context1.Context, *CommitReq) (*CommitRsp, error)
}

func RegisterMetadServer(s *grpc1.Server, srv MetadServer) {
	s.RegisterService(&_Metad_serviceDesc, srv)
}

func _Metad_RegisterClient_Handler(srv interface{}, stream grpc1.ServerStream) error {
	return srv.(MetadServer).RegisterClient(&metadRegisterClientServer{stream})
}

type Metad_RegisterClientServer interface {
	Send(*RegisterClientRsp) error
	Recv() (*RegisterClientReq, error)
	grpc1.ServerStream
}

type metadRegisterClientServer struct {
	grpc1.ServerStream
}

func (x *metadRegisterClientServer) Send(m *RegisterClientRsp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metadRegisterClientServer) Recv() (*RegisterClientReq, error) {
	m := new(RegisterClientReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Metad_RegisterNode_Handler(srv interface{}, stream grpc1.ServerStream) error {
	return srv.(MetadServer).RegisterNode(&metadRegisterNodeServer{stream})
}

type Metad_RegisterNodeServer interface {
	Send(*RegisterNodeRsp) error
	Recv() (*RegisterNodeReq, error)
	grpc1.ServerStream
}

type metadRegisterNodeServer struct {
	grpc1.ServerStream
}

func (x *metadRegisterNodeServer) Send(m *RegisterNodeRsp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metadRegisterNodeServer) Recv() (*RegisterNodeReq, error) {
	m := new(RegisterNodeReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Metad_CreateNamespace_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadServer).CreateNamespace(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadpb.Metad/CreateNamespace",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(MetadServer).CreateNamespace(ctx, req.(*CreateNamespaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metad_DropNamespace_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropNamespaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadServer).DropNamespace(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadpb.Metad/DropNamespace",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(MetadServer).DropNamespace(ctx, req.(*DropNamespaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metad_AddNodeToNamespace_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeToNamespaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadServer).AddNodeToNamespace(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadpb.Metad/AddNodeToNamespace",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(MetadServer).AddNodeToNamespace(ctx, req.(*AddNodeToNamespaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metad_RemoveNodeFromNamespace_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeFromNamespaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadServer).RemoveNodeFromNamespace(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadpb.Metad/RemoveNodeFromNamespace",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(MetadServer).RemoveNodeFromNamespace(ctx, req.(*RemoveNodeFromNamespaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metad_AutoBalance_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadServer).AutoBalance(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadpb.Metad/AutoBalance",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(MetadServer).AutoBalance(ctx, req.(*AutoBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metad_MigrateShard_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateShardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadServer).MigrateShard(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadpb.Metad/MigrateShard",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(MetadServer).MigrateShard(ctx, req.(*MigrateShardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metad_Info_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadServer).Info(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadpb.Metad/Info",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(MetadServer).Info(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metad_Commit_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadServer).Commit(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadpb.Metad/Commit",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(MetadServer).Commit(ctx, req.(*CommitReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metad_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "metadpb.Metad",
	HandlerType: (*MetadServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "CreateNamespace",
			Handler:    _Metad_CreateNamespace_Handler,
		},
		{
			MethodName: "DropNamespace",
			Handler:    _Metad_DropNamespace_Handler,
		},
		{
			MethodName: "AddNodeToNamespace",
			Handler:    _Metad_AddNodeToNamespace_Handler,
		},
		{
			MethodName: "RemoveNodeFromNamespace",
			Handler:    _Metad_RemoveNodeFromNamespace_Handler,
		},
		{
			MethodName: "AutoBalance",
			Handler:    _Metad_AutoBalance_Handler,
		},
		{
			MethodName: "MigrateShard",
			Handler:    _Metad_MigrateShard_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Metad_Info_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Metad_Commit_Handler,
		},
	},
	Streams: []grpc1.StreamDesc{
		{
			StreamName:    "RegisterClient",
			Handler:       _Metad_RegisterClient_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RegisterNode",
			Handler:       _Metad_RegisterNode_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "metad.proto",
}

func init() { proto.RegisterFile("metad.proto", fileDescriptor_metad_6f03260f97e5f353) }

var fileDescriptor_metad_6f03260f97e5f353 = []byte{
	// 788 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xae, 0xd3, 0x7c, 0x34, 0x93, 0xba, 0x49, 0xe6, 0x7d, 0xa1, 0xae, 0x5b, 0x50, 0xb5, 0x20,
	0x35, 0x48, 0x28, 0xb4, 0xe1, 0x0a, 0x87, 0xd0, 0xa8, 0x34, 0x87, 0xe6, 0x60, 0x0a, 0x17, 0x4e,
	0x9b, 0x78, 0x1b, 0x22, 0xc5, 0xde, 0xc5, 0xeb, 0x82, 0xfa, 0x03, 0x90, 0xb8, 0x72, 0xe6, 0xe7,
	0xf1, 0x27, 0x38, 0x22, 0xaf, 0x3f, 0x62, 0x3b, 0x71, 0x9b, 0x0a, 0x71, 0x8a, 0x67, 0x9e, 0xf9,
	0xda, 0xd9, 0x99, 0x67, 0x03, 0x0d, 0x87, 0xf9, 0xd4, 0xee, 0x0a, 0x8f, 0xfb, 0x1c, 0x6b, 0x4a,
	0x10, 0x63, 0x72, 0x02, 0x6d, 0x8b, 0x4d, 0x67, 0xd2, 0x67, 0xde, 0xe9, 0x7c, 0xc6, 0x5c, 0xdf,
	0x62, 0x9f, 0xf1, 0x00, 0xea, 0x2e, 0x75, 0x98, 0x14, 0x74, 0xc2, 0x0c, 0xed, 0x50, 0xeb, 0xd4,
	0xad, 0x85, 0x82, 0xbc, 0x5a, 0x72, 0x91, 0x02, 0x8f, 0xa0, 0xe2, 0xd3, 0xf1, 0x3c, 0x34, 0x6f,
	0xf4, 0xda, 0xdd, 0x28, 0x41, 0xf7, 0x22, 0xf8, 0xa5, 0x3e, 0xb5, 0x42, 0x9c, 0x7c, 0x2b, 0x41,
	0x33, 0x76, 0x1f, 0x71, 0x9b, 0x05, 0xf9, 0x4e, 0xa0, 0xec, 0xdf, 0x88, 0xd0, 0x77, 0xa7, 0xf7,
	0x28, 0xf1, 0xcd, 0xd9, 0x75, 0x2f, 0x6f, 0x04, 0xb3, 0x94, 0x29, 0x22, 0x94, 0xa9, 0x6d, 0x7b,
	0x46, 0x49, 0x55, 0xa7, 0xbe, 0xb3, 0x65, 0x6f, 0xe6, 0xca, 0x46, 0x03, 0x6a, 0x53, 0x8f, 0x5f,
	0x8b, 0xe1, 0xc0, 0x28, 0x1f, 0x6a, 0x1d, 0xdd, 0x8a, 0xc5, 0xc0, 0xcf, 0x63, 0x62, 0x3e, 0x9b,
	0xd0, 0xe1, 0xc0, 0xa8, 0x28, 0x6c, 0xa1, 0xc0, 0x87, 0x50, 0xf5, 0xb9, 0xcd, 0x87, 0x03, 0xa3,
	0xaa, 0xa0, 0x48, 0x22, 0xaf, 0xa1, 0x1c, 0xd4, 0x83, 0x6d, 0xd0, 0xe3, 0x3a, 0xdf, 0x7d, 0xa2,
	0x9e, 0xdd, 0xda, 0xc0, 0xff, 0xa0, 0xf9, 0xde, 0xf5, 0x32, 0x4a, 0x0d, 0x75, 0xa8, 0x9f, 0x33,
	0xea, 0xf9, 0x63, 0x46, 0xfd, 0x56, 0x89, 0x7c, 0xd7, 0x72, 0x7d, 0x90, 0x62, 0xbd, 0x3e, 0x48,
	0x91, 0xee, 0x83, 0x01, 0x35, 0x19, 0x24, 0x18, 0x0e, 0xa2, 0x56, 0xc4, 0x22, 0xe9, 0x44, 0xf5,
	0x35, 0xa1, 0x71, 0xea, 0x31, 0xea, 0xb3, 0xb8, 0xba, 0x26, 0x34, 0x2c, 0xe6, 0xf0, 0x2f, 0x91,
	0x42, 0x23, 0x3e, 0x60, 0x68, 0x31, 0x8a, 0x9b, 0x75, 0xe7, 0x10, 0xa0, 0x09, 0x5b, 0x2a, 0xd1,
	0xe8, 0xda, 0x51, 0x89, 0x75, 0x2b, 0x91, 0xf1, 0x29, 0xe8, 0x51, 0xfb, 0xce, 0xe8, 0xc4, 0xe7,
	0x9e, 0xba, 0x0b, 0xdd, 0xca, 0x2a, 0xc9, 0xff, 0xcb, 0x59, 0xa5, 0x20, 0xc7, 0xd0, 0x1a, 0x78,
	0x5c, 0xac, 0x5f, 0x09, 0xc1, 0xbc, 0x87, 0x14, 0x64, 0x0a, 0x0f, 0xfa, 0xb6, 0x1d, 0xb4, 0xeb,
	0x92, 0xdf, 0xe3, 0x50, 0x05, 0x43, 0x45, 0x6d, 0x67, 0xe6, 0xf6, 0x03, 0x20, 0x1a, 0xaa, 0x44,
	0x41, 0x76, 0x57, 0x26, 0x92, 0x82, 0x8c, 0xc0, 0x0c, 0x9b, 0x1c, 0x60, 0x67, 0x1e, 0x77, 0xfe,
	0xae, 0x0c, 0x72, 0x50, 0x1c, 0x4f, 0x0a, 0xf2, 0x43, 0x83, 0x3d, 0x8b, 0x89, 0x39, 0x9d, 0x28,
	0x7c, 0xe8, 0xde, 0x23, 0x9b, 0x01, 0x35, 0x3e, 0xb7, 0xfb, 0x8b, 0x84, 0xb1, 0x18, 0x20, 0x2e,
	0xfb, 0x9a, 0x3a, 0x78, 0x2c, 0x22, 0x81, 0x6d, 0xf5, 0x19, 0xf7, 0xa5, 0xac, 0xe0, 0x8c, 0x8e,
	0xec, 0x17, 0x96, 0x24, 0x05, 0xe9, 0xc2, 0x4e, 0xff, 0xda, 0xe7, 0x6f, 0xe8, 0x9c, 0xba, 0xeb,
	0x5c, 0x72, 0x2b, 0x6b, 0x2f, 0x05, 0xf9, 0xa9, 0x41, 0xf3, 0x62, 0x36, 0xf5, 0xe2, 0xc1, 0x5e,
	0xeb, 0xa0, 0xe9, 0x55, 0xd1, 0x93, 0x55, 0xc9, 0x12, 0xc0, 0x66, 0x9e, 0x00, 0x4c, 0xd8, 0xba,
	0x0a, 0x1a, 0xce, 0x6d, 0x16, 0x1d, 0x34, 0x91, 0x43, 0x72, 0x50, 0x48, 0x45, 0x21, 0x91, 0x44,
	0xda, 0xb9, 0xe2, 0xa4, 0x20, 0x47, 0x50, 0x1b, 0xba, 0x57, 0xfc, 0xee, 0xb3, 0xd6, 0x23, 0x43,
	0x29, 0xc8, 0x33, 0xa8, 0x9f, 0x72, 0xc7, 0x99, 0xad, 0xc1, 0xca, 0x8d, 0xc4, 0x54, 0x0a, 0xf2,
	0x5b, 0x83, 0xad, 0x98, 0x78, 0xff, 0xf5, 0x22, 0xe3, 0x0b, 0xa8, 0x2a, 0x0f, 0x69, 0x94, 0x0f,
	0x37, 0x3b, 0x8d, 0xde, 0xee, 0x12, 0xf7, 0x77, 0xc3, 0x26, 0x44, 0x66, 0xe6, 0x47, 0xa8, 0x28,
	0x45, 0x9a, 0x92, 0xb5, 0x5b, 0x28, 0xb9, 0xb4, 0xe2, 0x46, 0x5c, 0x6e, 0xb3, 0xd4, 0x64, 0x26,
	0x72, 0xef, 0x57, 0x05, 0x2a, 0x2a, 0x2f, 0x8e, 0x60, 0x27, 0xfb, 0x4e, 0xa1, 0xb9, 0xc4, 0xa8,
	0xc9, 0x9b, 0x67, 0x16, 0x62, 0x52, 0x90, 0x8d, 0x8e, 0x76, 0xac, 0xe1, 0x39, 0x6c, 0xa7, 0x89,
	0x18, 0x8d, 0xa2, 0x77, 0xca, 0x34, 0x8a, 0x98, 0x3b, 0x8a, 0x74, 0x01, 0xcd, 0x1c, 0xf5, 0xe1,
	0x7e, 0xe2, 0xb2, 0x4c, 0xc5, 0x66, 0x31, 0x18, 0x84, 0xc4, 0xb7, 0xa0, 0x67, 0x18, 0x10, 0xf7,
	0x12, 0xfb, 0x3c, 0x97, 0x9a, 0x45, 0x90, 0x0a, 0xf4, 0x01, 0x70, 0x99, 0xcd, 0xf0, 0x71, 0xe2,
	0xb2, 0x92, 0x53, 0xcd, 0x5b, 0x71, 0x15, 0x97, 0xc1, 0x6e, 0x01, 0x79, 0xe1, 0x93, 0x54, 0xab,
	0x8a, 0xe8, 0xd2, 0xbc, 0xdb, 0x48, 0xa5, 0xe9, 0x43, 0x23, 0x45, 0x12, 0xb8, 0x98, 0xc3, 0x2c,
	0xd5, 0x98, 0xab, 0x01, 0x15, 0x62, 0x00, 0xdb, 0xe9, 0xbd, 0x4d, 0xdd, 0x71, 0x8e, 0x6b, 0xcc,
	0x02, 0x44, 0x45, 0x79, 0x0e, 0xe5, 0x60, 0x83, 0xb1, 0x95, 0xd8, 0x44, 0x9b, 0x6f, 0xe6, 0x34,
	0xca, 0xba, 0x07, 0xd5, 0x70, 0x73, 0x11, 0x17, 0xf7, 0x1c, 0x6f, 0xbd, 0xb9, 0xa4, 0x0b, 0x7c,
	0xc6, 0x55, 0xf5, 0x37, 0xee, 0xe5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x70, 0x14, 0xc7,
	0xd5, 0x09, 0x00, 0x00,
}
